### ISSUE TITLE
stop

### ISSUE THREAD

**Issue by qubodup** [jazztickets/irrlamb#10]
"advanced tutorial" you say?
![1448646447-](https://cloud.githubusercontent.com/assets/18312/11446449/6820f3e8-9537-11e5-9f29-cbd4b4252037.png)
If the game is going to throw a 1999's Driver hardness style level at the player and call it "tutorial", then at least give them a way to stop the ball please other than yanking the ball back and forth for tens of seconds.

**Comment by jazztickets** [comment]
It should actually be part of a section called "Extreme Tutorials" =)

If you can beat my record i'll buy ya a cookie.

![2015-11-27-121151_1920x1080_scrot](https://cloud.githubusercontent.com/assets/425930/11447260/a2ce6598-9500-11e5-90f0-0d475fecb6ae.png)
