### ISSUE TITLE
Can get stuck below cushion in House level

### ISSUE THREAD

**Issue by Wuzzy2** [jazztickets/irrlamb#15]
I managed to get stuck below the cushion in the level “House”:

https://satoshiupload.com/images/ES33fYJmyZ.png

Impossible to move in any direction or jump. The only way out is a hard reset. :-(

Version 1.0.0

**Comment by jazztickets** [comment]
Brutal! Fixed in 03f83928543fceeda0975c1e3da21ebf51803760
