### ISSUE TITLE
Disabling tutorial messages disables all level messages

### ISSUE THREAD

**Issue by Wuzzy2** [jazztickets/irrlamb#16]
If you disable the tutorial messages in the settings, this disables ALL level messages.

This is not good because:
a) The setting does not do as advertised
b) Some level messages are very important and should IMO never be hidden (e.g. in the level “House” when you have to flush the toilet. If tutorial messages are disabled, you will have no idea what you must do next).

IMO this setting should really only disable real tutorial messages, but not other messages.

Version 1.0.0

**Comment by jazztickets** [comment]
Funny cause i was thinking the same thing when i added that option, then i'm like "nah, nobody will ever care" and here we are.

**Comment by Wuzzy2** [comment]
Or just remove the option. xD

**Comment by jazztickets** [comment]
Nah it's all good. Fixed in master.
