### ISSUE TITLE
Odd level selection when messing with secret level

### ISSUE THREAD

**Issue by Wuzzy2** [jazztickets/irrlamb#17]
There is an odd/slightly buggy level selection menu when you follow these precise steps:

Steps to reproduce:

* Enter the secret level (psst!)
* Win
* Click “Next Level”
* You're now in a weird place
* Hit Esc and “Quit to main menu”

Now you see what apparently seems to a special level set. Strangely, the first level (I believe this must be the secret level you just won) is locked while the second level can be accessed.

Version 1.0.0

**Comment by jazztickets** [comment]
Ah, good catch. I guess you could say I was on "drug" at the time. Fixed in master.
