### ISSUE TITLE
Readd support for lua 5.2

### ISSUE THREAD

**Issue by akien-mga** [jazztickets/irrlamb#3]
In this commit you forced the usage of lua 5.3: https://github.com/jazztickets/irrlamb/commit/e70d211717a8d852a93942aa7049d9df9a6fdc41#diff-af3b638bc2a3e6c650974192a53c7291

However it does not seem to be motivated by any code change, and reverting the part that enforces lua 5.3 seems to work just as well. I guess the main motivation was that your distro is now providing lua 5.3 by default, but that's not the case of all distros yet, so it would be nice if you could add support for both 5.2 and 5.3.

**Comment by jazztickets** [comment]
i've added a LUA_VERSION var to cmake. So you would now do "cmake ../ -DLUA_VERSION=5.2" if you were running say ubuntu 15.04.

The problem was if you had 5.3 and 5.2 on your system, cmake would find the lib for 5.2 but use the 5.3 header files.
