### ISSUE TITLE
assets dir seems unused

### ISSUE THREAD

**Issue by akien-mga** [jazztickets/irrlamb#4]
In previous versions it seems that the game data was in assets/, while WIP or assets source was in working/.

With 0.2.0 however, assets/ does not seem to be used anymore, as it's the content of working/ that gets make install'ed.

Could you clarify this, and maybe drop assets/ from the repo if it's no longer in use?

**Comment by jazztickets** [comment]
assets/ is still used for development. I just need to make a custom src.tar.gz for next version instead of an auto snapshot that github does (assuming that's possible with github).

**Comment by akien-mga** [comment]
Thanks for the clarification. You can indeed upload a custom tarball when drafting a new release/tag.

**Comment by jazztickets** [comment]
Fixed in next version
