### ISSUE TITLE
Mouse moves to corner

### ISSUE THREAD

**Issue by Nudin** [jazztickets/irrlamb#5]
When starting the game the mouse moves to the upper left corner of the screen and can't be used anymore. The game thus is unplayable.

---
From stout:

```
irrlamb 0.2.0
1 joystick(s) found.
Joystick 0
	Name: Microsoft Microsoft® Digital Media Pro Keyboard
	Axes: 37
	Buttons: 75
	Hat is unknown
Irrlicht Engine version 1.8.3
Linux 4.1.7.201509131604-1-grsec #1 SMP PREEMPT Mon Sep 14 00:45:54 EDT 2015 x86_64
Using renderer: OpenGL 3.0
Mesa DRI Intel(R) Ivybridge Desktop : Intel Open Source Technology Center
OpenGL driver version is 1.2 or better.
GLSL version: 1.3
_Audio::Init - Initializing audio
_Campaign::Init - Loading file irrlamb.xml

```

**Comment by jazztickets** [comment]
Guess irrlicht thinks your keyboard is a joystick. Awesome.

open up ~/.local/share/irrlamb/config.xml and change joystick_enabled="0"

**Comment by jazztickets** [comment]
In the next version you will be able to disable erroneous joysticks individually in case you do still want to use a gamepad.

**Comment by Nudin** [comment]
Worked. Thanks!
